In [1]:
! ../keras-retinanet/keras_retinanet/bin/train.py --weights data/resnet50_coco_best_v2.1.0.h5 \
--batch-size 2 --steps 500 --epochs 30 \
--snapshot-path data/snapshots_penguin/noresize \
--random-transform \
--config config_penguin/config.ini \
csv data/mosaics/labeled_tiles_penguin/train_annotations_final.csv data/mosaics/labeled_tiles_penguin/classes.csv \
--val-annotations data/mosaics/labeled_tiles_penguin/val_annotations_final.csv

Using TensorFlow backend.
2020-05-26 16:26:39.704987: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-05-26 16:26:39.748167: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
COMET INFO: old comet version (3.1.4) detected. current: 3.1.8 please update your comet lib with command: `pip install --no-cache-dir --upgrade comet_ml`
COMET WARNING: Failing to collect the installed os packages
COMET INFO: Experiment is live on comet.ml https://www.comet.ml/madelinehayes/steeple-jason/30ebd398a8f140c29006f4975fe9ce5c

Creating model, this may take a second...
2020-05-26 16:26:43.961047: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-05-26 16:26:43.974794: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but th

tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[-16.174623 , -11.597205 ,  16.174623 ,  11.597205 ],
       [-40.209812 , -28.830435 ,  40.209812 ,  28.830435 ],
       [-51.396    , -36.850933 ,  51.396    ,  36.850933 ],
       [-13.696    , -13.696    ,  13.696    ,  13.696    ],
       [-34.048    , -34.048    ,  34.048    ,  34.048    ],
       [-43.52     , -43.52     ,  43.52     ,  43.52     ],
       [-11.5918045, -16.18216  ,  11.5918045,  16.18216  ],
       [-28.817009 , -40.228546 ,  28.817009 ,  40.228546 ],
       [-36.83377  , -51.419945 ,  36.83377  ,  51.419945 ]],
      dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[ -32.349247,  -23.19441 ,   32.349247,   23.19441 ],
       [ -80.419624,  -57.66087 ,   80.419624,   57.66087 ],
       [-102.792   ,  -73.701866,  102.792   ,   73.701866],
       [ -27.392   ,  -27.392   ,   27.392   ,   27.392   ],
       [ -68.096   ,  -68.096   ,   

res4a_branch2a (Conv2D)         (None, None, None, 2 131072      res3d_relu[0][0]                 
__________________________________________________________________________________________________
bn4a_branch2a (BatchNormalizati (None, None, None, 2 1024        res4a_branch2a[0][0]             
__________________________________________________________________________________________________
res4a_branch2a_relu (Activation (None, None, None, 2 0           bn4a_branch2a[0][0]              
__________________________________________________________________________________________________
padding4a_branch2b (ZeroPadding (None, None, None, 2 0           res4a_branch2a_relu[0][0]        
__________________________________________________________________________________________________
res4a_branch2b (Conv2D)         (None, None, None, 2 589824      padding4a_branch2b[0][0]         
__________________________________________________________________________________________________
bn4a_branc

__________________________________________________________________________________________________
res5c_branch2a (Conv2D)         (None, None, None, 5 1048576     res5b_relu[0][0]                 
__________________________________________________________________________________________________
bn5c_branch2a (BatchNormalizati (None, None, None, 5 2048        res5c_branch2a[0][0]             
__________________________________________________________________________________________________
res5c_branch2a_relu (Activation (None, None, None, 5 0           bn5c_branch2a[0][0]              
__________________________________________________________________________________________________
padding5c_branch2b (ZeroPadding (None, None, None, 5 0           res5c_branch2a_relu[0][0]        
__________________________________________________________________________________________________
res5c_branch2b (Conv2D)         (None, None, None, 5 2359296     padding5c_branch2b[0][0]         
__________

2020-05-26 16:27:03.417181: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
  1/500 [..............................] - ETA: 1:31:54 - loss: 4.3314 - regression_loss: 3.2873 - classification_loss: 1.0441COMET INFO: Ignoring automatic log_metric('batch_batch') because 'keras:batch_batch' is in COMET_LOGGING_METRICS_IGNORE
COMET INFO: Ignoring automatic log_metric('batch_size') because 'keras:batch_size' is in COMET_LOGGING_METRICS_IGNORE
500/500 [==============================] - 92s 184ms/step - loss: 3.0442 - regression_loss: 2.3018 - classification_loss: 0.7424
Running network: 100% (119 of 119) |#####| Elapsed Time: 0:00:07 Time:  0:00:07
Parsing annotations: 100% (119 of 119) |#| Elapsed Time: 0:00:00 Time:  0:00:00
1285 instances of class penguin with average precision: 0.1650
mAP: 0.1650

Epoch 00001: saving model to data/snapshots_penguin/noresize/resnet50_csv_01.h5
Epoch 2/30
500/500 [===========================

Epoch 14/30
500/500 [==============================] - 80s 159ms/step - loss: 1.7338 - regression_loss: 1.4373 - classification_loss: 0.2964: 1:08 - loss: 1.7424 - re - ETA: 53s - loss: 1.7736 - regression_loss: 1.4763 - classificatio - ETA: 52s - loss: 1.7607 - - ETA: 41s - loss: 1.7457 - E
Running network: 100% (119 of 119) |#####| Elapsed Time: 0:00:05 Time:  0:00:05
Parsing annotations: 100% (119 of 119) |#| Elapsed Time: 0:00:00 Time:  0:00:00
1285 instances of class penguin with average precision: 0.6623
mAP: 0.6623

Epoch 00014: saving model to data/snapshots_penguin/noresize/resnet50_csv_14.h5
Epoch 15/30
500/500 [==============================] - 80s 159ms/step - loss: 1.6829 - regression_loss: 1.4042 - classification_loss: 0.2787: 1:08 - ETA:  - ETA: 52s - loss: 1.7010 - regression_loss: 1.4043 - classificat - ETA: 51s - loss: 1.6984 - regress - ETA: 47s - loss: 1.6894 - regress - ETA: 43s - loss: 1.6893 - regression_loss - ETA - ETA: 15s -  - ETA: 9s - loss: 1.6749 - regress

500/500 [==============================] - 79s 157ms/step - loss: 1.5711 - regression_loss: 1.3212 - classification_loss: 0.2499: 1:14 - loss: 1.5359 - regression_loss:  - ETA: 1:08 - loss: 1.4777 - regression_loss: 1.2504 - classi - ETA: 1:05 - loss: 1.4560 - regression_loss: 1.2262 - classification_ - ETA: 1:03 - loss: 1.4844 - regression_loss: 1.2514 - classification_los - ETA: 1:02 - loss: 1.5016 - regres - ETA: 50s - loss: 1.5500 - regression_loss: 1.3041 - classif - ETA: 49s - loss: 1.5499 - regress - ETA: 45s - loss: 1.5691 - ETA: 41s - loss: 1.5586 - regression_loss: 1.3137 - class - ETA: 39s - loss: 1.5537 - regression_loss: 1.3082 - cla - ETA: 37s - loss: 1.5567 - regress - ETA: 34s  - ETA: 28s - loss: 1.55 - ETA: 24s - loss: 1.5601 - regression_loss: 1.3106 - classificat - ETA: 22s - loss: 1.5670 - regression_loss: 1.3169 - class - ETA: 21s - loss: 1.5640 - regression_ - ETA: 17s - loss: 1.5637 - regression_loss: 1.3150 - class - ETA: 16s - loss:  - ETA: 11s - loss: 1.5646 -

In [2]:
! ../keras-retinanet/keras_retinanet/bin/convert_model.py --config config_penguin/config.ini data/snapshots_penguin/noresize/resnet50_csv_30.h5 data/snapshots_penguin/noresize/final_model_penguin_noresize.h5

Using TensorFlow backend.
2020-05-26 17:11:56.592472: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-05-26 17:11:56.597752: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
2020-05-26 17:11:57.632048: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-05-26 17:11:57.646321: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-26 17:11:57.646668: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1060 computeCapability: 6.1
coreClock: 1.6705GHz coreCount: 10 deviceMemorySize: 5.94GiB deviceMemoryBandwidth: 178.99GiB/s
2020-05-26 17:11:57.646707: I tenso

In [3]:
! ../keras-retinanet/keras_retinanet/bin/evaluate.py --config config_penguin/config.ini csv data/mosaics/labeled_tiles_penguin/test_annotations_final.csv data/mosaics/labeled_tiles_penguin/classes.csv data/snapshots_penguin/noresize/final_model_penguin_noresize.h5 

Using TensorFlow backend.
2020-05-26 17:12:38.754960: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-05-26 17:12:38.756070: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
Loading model, this may take a second...
2020-05-26 17:12:39.593604: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-05-26 17:12:39.601795: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-26 17:12:39.602053: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1060 computeCapability: 6.1
coreClock: 1.6705GHz coreCount: 10 deviceMemorySize: 5.94GiB deviceMemoryBandwidth: 178.99

/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py:341: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
Running network: N/A% (0 of 126) |       | Elapsed Time: 0:00:00 ETA:  --:--:--2020-05-26 17:12:43.080593: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-05-26 17:12:43.768073: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
Running network: 100% (126 of 126) |#####| Elapsed Time: 0:00:24 Time:  0:00:24
Parsing annotations: 100% (126 of 126) |#| Elapsed Time: 0:00:00 Time:  0:00:00
1243 instances of class penguin with average precision: 0.1665
Inference time for 126 images: 0.1601
mAP using the weighted average of precisions among classes: 0.1665
mAP: 0.1665


In [4]:
! ../keras-retinanet/keras_retinanet/bin/evaluate.py --config config_penguin/config.ini csv data/mosaics/labeled_tiles_penguin/val_annotations_final.csv data/mosaics/labeled_tiles_penguin/classes.csv data/snapshots_penguin/noresize/final_model_penguin_noresize.h5 

Using TensorFlow backend.
2020-05-26 17:13:19.220671: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-05-26 17:13:19.221753: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
Loading model, this may take a second...
2020-05-26 17:13:20.011373: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-05-26 17:13:20.027476: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-26 17:13:20.028023: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1060 computeCapability: 6.1
coreClock: 1.6705GHz coreCount: 10 deviceMemorySize: 5.94GiB deviceMemoryBandwidth: 178.99

/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py:341: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
Running network: N/A% (0 of 119) |       | Elapsed Time: 0:00:00 ETA:  --:--:--2020-05-26 17:13:23.800580: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-05-26 17:13:24.455651: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
Running network: 100% (119 of 119) |#####| Elapsed Time: 0:00:23 Time:  0:00:23
Parsing annotations: 100% (119 of 119) |#| Elapsed Time: 0:00:00 Time:  0:00:00
1285 instances of class penguin with average precision: 0.1590
Inference time for 119 images: 0.1646
mAP using the weighted average of precisions among classes: 0.1590
mAP: 0.1590


In [1]:
%matplotlib inline

%reload_ext autoreload
%autoreload 2

import keras

from keras_retinanet.models import retinanet
from keras_retinanet import models
from keras_retinanet.utils.image import read_image_bgr, preprocess_image, resize_image
from keras_retinanet.utils.visualization import draw_box, draw_caption
from keras_retinanet.utils.colors import label_color

import matplotlib.pyplot as plt
import cv2
import os
import numpy as np
import time
import json
from random import shuffle

import tensorflow as tf

def get_session():
    config = tf.compat.v1.ConfigProto()
    config.gpu_options.allow_growth = True
    return tf.compat.v1.Session(config=config)

tf.compat.v1.keras.backend.set_session(get_session())

Using TensorFlow backend.


In [2]:
model_path = 'data/snapshots_penguin/final/final_model_penguin_nms5.h5'

print(model_path)

model = models.load_model(model_path, backbone_name='resnet50')

print(model.summary())

labels_to_names = {0: 'penguin'}

data/snapshots_penguin/final/final_model_penguin_nms5.h5
tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[ -8.087312 ,  -5.7986026,   8.087312 ,   5.7986026],
       [-20.104906 , -14.415217 ,  20.104906 ,  14.415217 ],
       [-25.698    , -18.425467 ,  25.698    ,  18.425467 ],
       [ -6.848    ,  -6.848    ,   6.848    ,   6.848    ],
       [-17.024    , -17.024    ,  17.024    ,  17.024    ],
       [-21.76     , -21.76     ,  21.76     ,  21.76     ],
       [ -5.7959023,  -8.09108  ,   5.7959023,   8.09108  ],
       [-14.4085045, -20.114273 ,  14.4085045,  20.114273 ],
       [-18.416885 , -25.709972 ,  18.416885 ,  25.709972 ]],
      dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[-16.174623 , -11.597205 ,  16.174623 ,  11.597205 ],
       [-40.209812 , -28.830435 ,  40.209812 ,  28.830435 ],
       [-51.396    , -36.850933 ,  51.396    ,  36.850933 ],
       [-13.696    , -13.696    ,  13.69

/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py:341: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '


In [3]:
image_dir = "data/mosaics/GrandJason_SWLeftThird_Nov2019_transparent_mosaic_group1_250x250_overlap20/"

image_list = []
for root, dirs, files in os.walk(image_dir):
    for filename in files:
        if filename.lower().endswith(('.png')):
            image_list.append(image_dir + filename)
print(len(image_list))

24255


In [4]:
visualize = True
min_score = 0.5

detections = {}

total_time = 0

count = 0
detection_iterations = 10
shuffle(image_list)

for image_path in image_list: 
    if count > detection_iterations:
        break
    else: 
        count +=1
    
    image = read_image_bgr(image_path)
    
    if visualize:
        draw = image.copy()
        draw = cv2.cvtColor(draw, cv2.COLOR_BGR2RGB)
        
    image = preprocess_image(image)
    image, scale = resize_image(image)
    
    start = time.time()
    boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))
    total_time += time.time() - start 
    
    boxes /= scale
    if any(score >= min_score for score in scores [0]):
        detections[image_path] = []
        
    for box, score, label in zip(boxes[0], scores[0], labels[0]):
        if score < min_score:
            break
            
        b = box.astype(int)
        detections[image_path].append({"box" : b, "label" : label, "score" : score})
        
        if visualize: 
            color = label_color(label)
            
            draw_box(draw, b, color=color)
            
            caption = "{} {:.3f}".format(labels_to_names[label], score)
            draw_caption(draw, b, caption)
            
    if any(score >= min_score for score in scores[0]):
        if visualize:
            plt.figure(figsize=(10, 10))
            plt.axis('off')
            plt.imshow(draw)
            plt.show()
            
print("Finished, time per image:", total_time/len(image_list))

Finished, time per image: 0.00025791008185907825


In [5]:
min_score = 0.5

detections = {}

total_time = 0

for image_path in image_list:
    
    image = read_image_bgr(image_path)
          
    image = preprocess_image(image)
    image, scale = resize_image(image)
    
    start = time.time()
    boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))
    total_time += time.time() - start
    
    boxes /= scale 
        
    if any(score >= min_score for score in scores[0]):
        detections[image_path] = []
    
    #boxes = non_max_suppression_fast(boxes[0], 0.1)
    
    for box, score, label in zip(boxes[0], scores[0], labels[0]):
        if score < min_score:
            break
        
        b = box.astype(int)    
        #pick = non_max_suppression_fast(boxes, 0.3)
        detections[image_path].append({"box" : b, "label" : label, "score" : score})
        
            
print("Finished, time per image:", total_time/len(image_list))

Finished, time per image: 0.12344436928602229


In [6]:
class MyEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        elif isinstance(obj, np.floating):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        else:
            return super(MyEncoder, self).default(obj)

In [7]:
with open('data/detections_penguin/final/overlap20/detections_grandjason_swleftthird_250x250_overlap20.json', 'w') as fp:
    json.dump(detections, fp, cls=MyEncoder)